owner: LinkviteApp 
repo: status 

sites:
  - name: Linkvite API
    url: https://api.linkvite.io/health
assignees: # Users to assign downtime issues (optional)
  - kayode0x

status-website:
  cname: status.linkvite.io
  logoUrl: https://assets.linkvite.io/covers/default.png
  name: Linkvite
  introTitle: "Easiest way to save and organize your bookmarks."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/LinkviteApp/status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
